/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegistarRouteImport } from './routes/_auth.registar'
import { Route as AuthRecuperarRouteImport } from './routes/_auth.recuperar'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthEmpresaRouteImport } from './routes/_auth.empresa'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRhRouteImport } from './routes/_app.rh'
import { Route as AppLotesRouteImport } from './routes/_app.lotes'
import { Route as AppInventarioRouteImport } from './routes/_app.inventario'
import { Route as AppFornecedoresRouteImport } from './routes/_app.fornecedores'
import { Route as AppFaturacaoRouteImport } from './routes/_app.faturacao'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContabilidadeRouteImport } from './routes/_app.contabilidade'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppFaturacaoIdRouteImport } from './routes/_app.faturacao.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistarRoute = AuthRegistarRouteImport.update({
  id: '/registar',
  path: '/registar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmpresaRoute = AuthEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRhRoute = AppRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AppRoute,
} as any)
const AppLotesRoute = AppLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFaturacaoRoute = AppFaturacaoRouteImport.update({
  id: '/faturacao',
  path: '/faturacao',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContabilidadeRoute = AppContabilidadeRouteImport.update({
  id: '/contabilidade',
  path: '/contabilidade',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppFaturacaoIdRoute = AppFaturacaoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFaturacaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof AppClientesRoute
  '/contabilidade': typeof AppContabilidadeRoute
  '/dashboard': typeof AppDashboardRoute
  '/faturacao': typeof AppFaturacaoRouteWithChildren
  '/fornecedores': typeof AppFornecedoresRoute
  '/inventario': typeof AppInventarioRoute
  '/lotes': typeof AppLotesRoute
  '/rh': typeof AppRhRoute
  '/settings': typeof AppSettingsRoute
  '/empresa': typeof AuthEmpresaRoute
  '/login': typeof AuthLoginRoute
  '/recuperar': typeof AuthRecuperarRoute
  '/registar': typeof AuthRegistarRoute
  '/faturacao/$id': typeof AppFaturacaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof AppClientesRoute
  '/contabilidade': typeof AppContabilidadeRoute
  '/dashboard': typeof AppDashboardRoute
  '/faturacao': typeof AppFaturacaoRouteWithChildren
  '/fornecedores': typeof AppFornecedoresRoute
  '/inventario': typeof AppInventarioRoute
  '/lotes': typeof AppLotesRoute
  '/rh': typeof AppRhRoute
  '/settings': typeof AppSettingsRoute
  '/empresa': typeof AuthEmpresaRoute
  '/login': typeof AuthLoginRoute
  '/recuperar': typeof AuthRecuperarRoute
  '/registar': typeof AuthRegistarRoute
  '/faturacao/$id': typeof AppFaturacaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/clientes': typeof AppClientesRoute
  '/_app/contabilidade': typeof AppContabilidadeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/faturacao': typeof AppFaturacaoRouteWithChildren
  '/_app/fornecedores': typeof AppFornecedoresRoute
  '/_app/inventario': typeof AppInventarioRoute
  '/_app/lotes': typeof AppLotesRoute
  '/_app/rh': typeof AppRhRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/empresa': typeof AuthEmpresaRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recuperar': typeof AuthRecuperarRoute
  '/_auth/registar': typeof AuthRegistarRoute
  '/_app/faturacao/$id': typeof AppFaturacaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/contabilidade'
    | '/dashboard'
    | '/faturacao'
    | '/fornecedores'
    | '/inventario'
    | '/lotes'
    | '/rh'
    | '/settings'
    | '/empresa'
    | '/login'
    | '/recuperar'
    | '/registar'
    | '/faturacao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/contabilidade'
    | '/dashboard'
    | '/faturacao'
    | '/fornecedores'
    | '/inventario'
    | '/lotes'
    | '/rh'
    | '/settings'
    | '/empresa'
    | '/login'
    | '/recuperar'
    | '/registar'
    | '/faturacao/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/clientes'
    | '/_app/contabilidade'
    | '/_app/dashboard'
    | '/_app/faturacao'
    | '/_app/fornecedores'
    | '/_app/inventario'
    | '/_app/lotes'
    | '/_app/rh'
    | '/_app/settings'
    | '/_auth/empresa'
    | '/_auth/login'
    | '/_auth/recuperar'
    | '/_auth/registar'
    | '/_app/faturacao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/registar': {
      id: '/_auth/registar'
      path: '/registar'
      fullPath: '/registar'
      preLoaderRoute: typeof AuthRegistarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recuperar': {
      id: '/_auth/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/empresa': {
      id: '/_auth/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthEmpresaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rh': {
      id: '/_app/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AppRhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lotes': {
      id: '/_app/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof AppLotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario': {
      id: '/_app/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores': {
      id: '/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faturacao': {
      id: '/_app/faturacao'
      path: '/faturacao'
      fullPath: '/faturacao'
      preLoaderRoute: typeof AppFaturacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contabilidade': {
      id: '/_app/contabilidade'
      path: '/contabilidade'
      fullPath: '/contabilidade'
      preLoaderRoute: typeof AppContabilidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faturacao/$id': {
      id: '/_app/faturacao/$id'
      path: '/$id'
      fullPath: '/faturacao/$id'
      preLoaderRoute: typeof AppFaturacaoIdRouteImport
      parentRoute: typeof AppFaturacaoRoute
    }
  }
}

interface AppFaturacaoRouteChildren {
  AppFaturacaoIdRoute: typeof AppFaturacaoIdRoute
}

const AppFaturacaoRouteChildren: AppFaturacaoRouteChildren = {
  AppFaturacaoIdRoute: AppFaturacaoIdRoute,
}

const AppFaturacaoRouteWithChildren = AppFaturacaoRoute._addFileChildren(
  AppFaturacaoRouteChildren,
)

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppContabilidadeRoute: typeof AppContabilidadeRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFaturacaoRoute: typeof AppFaturacaoRouteWithChildren
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppLotesRoute: typeof AppLotesRoute
  AppRhRoute: typeof AppRhRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppContabilidadeRoute: AppContabilidadeRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFaturacaoRoute: AppFaturacaoRouteWithChildren,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppLotesRoute: AppLotesRoute,
  AppRhRoute: AppRhRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthEmpresaRoute: typeof AuthEmpresaRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
  AuthRegistarRoute: typeof AuthRegistarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmpresaRoute: AuthEmpresaRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
  AuthRegistarRoute: AuthRegistarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
